//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokemonSweeperMasterUWP.Strings.de {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DeResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DeResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PokemonSweeperMasterUWP.Strings.de.DeResources", typeof(DeResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurück.
        /// </summary>
        internal static string BackButton_Content {
            get {
                return ResourceManager.GetString("BackButton.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du hast das ganze Pokémon gefangen!.
        /// </summary>
        internal static string CaughtPokemon {
            get {
                return ResourceManager.GetString("CaughtPokemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprachen.
        /// </summary>
        internal static string LanguagesButton_Content {
            get {
                return ResourceManager.GetString("LanguagesButton.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprachauswahl.
        /// </summary>
        internal static string LanguageSelection_Text {
            get {
                return ResourceManager.GetString("LanguageSelection.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 1.
        /// </summary>
        internal static string Level1Button_Content {
            get {
                return ResourceManager.GetString("Level1Button.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 2.
        /// </summary>
        internal static string Level2Button_Content {
            get {
                return ResourceManager.GetString("Level2Button.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 3.
        /// </summary>
        internal static string Level3Button_Content {
            get {
                return ResourceManager.GetString("Level3Button.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to die Stufe.
        /// </summary>
        internal static string LevelTitle_Text {
            get {
                return ResourceManager.GetString("LevelTitle.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hauptmenü.
        /// </summary>
        internal static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PokemonSweeper.
        /// </summary>
        internal static string MainTitle_Text {
            get {
                return ResourceManager.GetString("MainTitle.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nächste Stufe.
        /// </summary>
        internal static string NextLevel {
            get {
                return ResourceManager.GetString("NextLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Hoffnung aufgeben.
        /// </summary>
        internal static string QuitButton_Content {
            get {
                return ResourceManager.GetString("QuitButton.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiederholen.
        /// </summary>
        internal static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rückgabestufen.
        /// </summary>
        internal static string ReturnLevels {
            get {
                return ResourceManager.GetString("ReturnLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Änderungen speichern.
        /// </summary>
        internal static string SaveChangesButton_Content {
            get {
                return ResourceManager.GetString("SaveChangesButton.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anfang.
        /// </summary>
        internal static string StartButton_Content {
            get {
                return ResourceManager.GetString("StartButton.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gut gemacht!.
        /// </summary>
        internal static string WellDone {
            get {
                return ResourceManager.GetString("WellDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du hast verloren!.
        /// </summary>
        internal static string YouLost {
            get {
                return ResourceManager.GetString("YouLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du hast gewonnen!.
        /// </summary>
        internal static string YouWon {
            get {
                return ResourceManager.GetString("YouWon", resourceCulture);
            }
        }
    }
}
